<?php $this->inlineScript()->appendFile($this->basePath() . '/js/search.js'); ?>
<h1>Index. Met Intelizoek</h1>


<?php
$form = $this->form;
$form->setAttribute('method','post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('name', 'memoForm');

$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
	<?php
	echo $this->formRow($form->get('search'));
	echo $this->formSubmit($form->get('submit'));
	?>
<?php
echo $this->form()->closeTag($form);
