<div id="buttons">
    <a href="<?php echo $this->url('overview', array('action' => 'new')); ?>"> new </a>
</div>
<?php 
$form = $this->form; 
$form->setAttribute('method','post');
$form->setAttribute('class', 'well');
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('memo'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('brand', 'prepend'));
echo $this->formRow($form->get('productGroups'), 'prepend');
echo $this->formRow($form->get('hechsheriem', 'prepend'));
echo $this->formRow($form->get('visible'), 'prepend');

echo $this->formInput($form->get('send'));
echo $this->form()->closeTag($form);


