<?php $this->inlineScript()->appendFile($this->basePath() . '/js/memo-form.js'); ?>

<script type="text/javascript">
    var isXmlHttpRequest    = <?php echo $this->isXmlHttpRequest; ?>;
    var urlform             = '<?php echo $this->url('zfcadmin/memo', array('controller'=>'memo', 'action'=>'validatepostajax')); ?>';
	var productId			= <?php echo $product->getId(); ?>
</script>
 
<div id="buttons">
    <a href="<?php echo $this->url('overview', array('action' => 'new')); ?>"> new </a>
    <span class="glyphicon .glyphicon-plus"></span>
</div>
<div class="page-header">
	<h1><?php echo $product->getProductName(); ?></h1>
</div>
<header>
<ul class="nav nav-tabs">
	<li class="active"><a href="#general" data-toggle="tab">General</a></li>
	<li><a href="#memos" data-toggle="tab">Notes</a></li>
</ul>
</header>
<div class="tab-content body">
    <div class="tab-pane active" id="general">
        <dl>
            <dt>Description</dt>
            <dd><?php echo $product->getDescription(); ?></dd>
            <dt>Merk</dt>
            <dd><?php echo $product->getBrand()->getBrandName(); ?></dd>
            <dt>Productgroups</dt>
            <dd>
                <?php
                foreach( $product->getProductGroups() as $productGroup):
                    echo $productGroup->getProductGroupName();
                endforeach;
                ?>

            </dd>
            <dt>Hechsheriem</dt>
            <dd>
                <?php
                foreach( $product->getHechsheriem() as $hechsher):
                    echo $hechsher->getHechsherName() . '<br/>';
                endforeach;
                ?>
            </dd>
        </dl>
    </div>
	<div class="tab-pane" id="memos">
		<div class="memos">
			<?php if($product->getMemos()){
				foreach($product->getMemos() as $memo){
					?>

					<div class="panel panel-default">
						<div class="panel-heading">
							<span>#<?php echo $memo->getId(); ?></span>
							<b><?php echo $memo->getCreated()->format('d-m-Y H:i')?></b>
							<?php $publiek = ($memo->getPublic() == 1) ? "Publiek" : "Prive";
								echo $publiek;
							?>
						</div>
						<div class="panel-body">
							<?php echo $memo->getMemo(); ?>
						</div>
					</div>
				<?php
				}
			}?>
		</div>
		<div>

			<?php
			$form = $this->memoForm;
			$form->setAttribute('method','post');
			$form->setAttribute('class', 'form-horizontal memoForm');
			$form->setAttribute('name', 'memoForm');
			$form->setAttribute('action', $this->url('zfcadmin/memo',
				array(
					'action' => 'postmemo',
					'conroller' => 'memo'
				)
			));
			$form->prepare();

			echo $this->form()->openTag($form);
			?>
			<div class="form-group">
				<?php
				echo $this->formRow($form->get('memo'));
				echo $this->formRow($form->get('public'));

				echo $this->formSubmit($form->get('send'));
				?>

				<?php
				echo $this->form()->closeTag($form);


				echo $this->memo ?>
			</div>

		</div>
	</div>

</div>
