<div id="buttons">
    <a href="<?php echo $this->url('overview', array('action' => 'new')); ?>"> new </a>
    <span class="glyphicon .glyphicon-plus"></span>
</div>





<ul class="nav nav-tabs">
    <li class="active"><a href="#general" data-toggle="tab">General</a></li>
    <li><a href="#memos" data-toggle="tab">Notes</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="general">
        <dl>
            <dt>Description</dt>
            <dd><?php echo $product->getDescription(); ?></dd>
            <dt>Merk</dt>
            <dd><?php echo $product->getBrand()->getBrandName(); ?></dd>
            <dt>Productgroups</dt>
            <dd>
                <?php
                foreach( $product->getProductGroups() as $productGroup):
                    echo $productGroup->getProductGroupName();
                endforeach;
                ?>

            </dd>
            <dt>Hechsheriem</dt>
            <dd>
                <?php
                foreach( $product->getHechsheriem() as $hechsher):
                    echo $hechsher->getHechsherName() . '<br/>';
                endforeach;
                ?>
            </dd>
        </dl>


    </div>
    <div class="tab-pane" id="memos">

        <?php if($product->getMemos()){
            foreach($product->getMemos() as $memo){
                echo $memo->getMemo();
            }
        }?>

    </div>
</div>














<div class="panel panel-default">
    <div class="panel-heading">
        <h2 class="panel-title"><?php echo $product->getProductName();?></h2>
    </div>

    <div class="panel-body">


    </div>
</div>