<?php
$form = $this->form;
$form->setAttribute('method','post');
$form->setAttribute('class', 'well');
$form->setAttribute('action', $this->url('zfcadmin/memo',
        array(
             'action' => 'postmemo',
            'conroller' => 'memo'
        )
));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('memo'));

echo $this->formSubmit(

 $form->get('send'));
echo $this->form()->closeTag($form);


