<h1>Product categorieën</h1>
<form class="form-search search-bar">
    <div class="input-append">
        <input type="text" class="search-query" placeholder="Enter your address here...">
        <button type="submit" class="btn btn-primary">
            Search <i class="icon-search icon-white"></i></button>
    </div>
</form>
<ul class="nav nav-tabs nav-stacked">
    <li><a href="">Bakproducten</a></li>
    <li><a href="">Dranken</a></li>
    <li><a href="">Vleesvervangers</a></li>
    <li><a href="">Chips en nootjes</a></li>
    <li><a href="">Babyvoeding</a></li>
    <li><a href="">Chocolade & bonbons</a></li>
    <li><a href="">Broodbeleg</a></li>
    <li><a href="">Chips en noten</a></li>
    <li><a href="">Drop</a></li>
</ul>

<?php echo 'blablabla'; ?>