<div class="modal fade" id="productVariantModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel">Create new variant</h4>
			</div>
			<div class="modal-body">

				<?php echo $this->content ?>
			</div>
			<div class="modal-footer">
				<?php
				echo $this->formRow($productVariantForm->get('send'));
				echo $this->form()->closeTag($productVariantForm);
				?>
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary save-shop">Save changes</button>
			</div>
		</div>
	</div>
</div>

