<!DOCTYPE html>
<html lang="nl">
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->headLink(array('rel'=>'stylesheet/less','href'=> '/Bootstrap/custom/main.less'),'PREPEND');
      //  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
	?>
	<!-- @todo fix me later-->

	<?php echo $this->headScript()
			//->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/less.js')
			->prependFile($this->basePath() . '/js/bootstrap.min.js')
			->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js')
			 ->prependFile($this->basePath() . '/js/jquery.min.js')
	?>

    <head>

</head>
    <body>
        <header>
            <div class="header-left-content"></div>
            <div class="header-right-content">
                <div class="login"> <?php //echo $this->zfcUserLoginWidget();?> </div>
                <div class="topmenu">
                    <ul class="topNav">
                        <li><span class="glyphicon glyphicon-cog"></span></li>
                        <li>test</li>
                        <li>test</li>
                     </ul>
                </div>
            </div>
        </header>
        <div class="content-container">
            <div class="content">
                <aside>
                        <?php  echo $this->navigation('admin_navigation')->render(null, array('ulClass' => 'nav nav-pills nav-stacked')); ?>
                </aside>
                <div class="right-side">

                    <?php if(count($this->flashMessages)) : ?>
                        <ul class="messages">
                            <?php foreach ($flashMessages as $msg) : ?>
                                <li><?php echo $msg; ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <?php echo $this->layout()->content; ?>


                </div>
            </div>
        </div>
		<?php echo $this->inlineScript() ?>
    </body>
</html>