
<table class="table  table-striped">
  <thead>
        <tr>
            <th>#</th>
            <th>Product name</th>
            <th>Brand name</th>
			<th>Tags</th>
			<th>Visible</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
   </thead>
   <tbody>
       <?php foreach($this->products as $product) : ?>
       
       <tr>
           <td> <?php echo $product->getId(); ?></td>
           <td> <a href="<?php echo $this->url('zfcadmin/product', array('action' => 'index', 'id' => $product->getId())); ?>" data-toggle="modal" title="edit"> <?php echo $product->getProductName(); ?></a></td>
           <?php if($product->getBrand()): ?>
                <td> <?php echo $product->getBrand()->getBrandName(); ?></td>
           <?php else:?>
               <td> &nbsp;</td>
           <?php endif; ?>

		    <?php
			$tagsStr = implode(', ', array_map(function ($tag) { return $tag->getTag(); }, $product->getTags()->toArray()));
			?>
		   <td> <?php echo $tagsStr ?></td>
           <td> <?php echo $product->getVisible() ? '<span class="label label-success">Yes</span>' : '<span class="label label-default">No</span>'; ?></td>
           <td> <a href="<?php echo $this->url('zfcadmin/product', array('action' => 'edit', 'id' => $product->getId())); ?>" title="edit">Edit</a></td>
           <td> <a href="<?php echo $this->url('zfcadmin/product', array('action' => 'delete', 'id' => $product->getId())); ?>" title="delete">delete</a></td>
           <td> <a href="<?php echo $this->url('zfcadmin/product', array('action' => 'delete', 'id' => $product->getId())); ?>" title="delete">Mark for Update</a></td>
       </tr>
       <?php endforeach ?>
   </tbody>
    
</table>


